config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'tasks', to: 'tasks#create', as: 'create_task'
  patch 'tasks/:id', to: 'tasks#update', as: 'update_task'
  delete 'tasks/:id', to: 'tasks#delete', as: 'delete_task'

  get 'tasks', to: 'tasks#index', as: 'tasks'
  get 'tasks/new', to: 'tasks#new', as: 'create_task_form' 
  get 'tasks/:id', to: 'tasks#find', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def find 
    @task = Task.find(params["id"])
  end

  def create
    @task = Task.new(task_attributes)
    @task.save
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params["id"])
  end
  
  def update
    @task = Task.find(params["id"])
    @task.update(task_attributes)
    @task.save
    redirect_to task_path(params["id"])
  end

  def delete
    @task = Task.find(params["id"])
    @task.destroy
    redirect_to tasks_path
  end

  private
  
  def task_attributes
    params.require(:task).permit(:title, :details, :completed)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_area :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/find.html.erb
<h1><%= @task.title %> </h1>
<%= link_to 'Edit this task', edit_task_path %>
<div class="banner">
  <p><%= @task.details %></p>
</div>
<div class="item-container">
  <input type="checkbox" name="checkbox" <%= "checked" if @task.completed %> >
  <label>This task is not completed</label>
</div>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <input type="checkbox" name="checkbox" <%= "checked" if task.completed %> >
      <%= link_to task_path(task.id) do %>
        <label><%= task.title %></label>
      <% end %>
      <div class="btn">
        <%= link_to 'Delete', delete_task_path(task.id), :method => 'delete'%>
      </div>
      
    </li>
  <% end %>
</ul>
<%= link_to 'Add new task', create_task_form_path %>

app/views/tasks/new.html.erb
<h1>hum is hum h</h1>
<%= render 'form', task: @task %>